auth-server:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/auth-server
    tag: 1.0.0_dev
  replicas: 1
  resources:
    limits:
      cpu: 2500m
      memory: 2500Mi
    requests:
      cpu: 2500m
      memory: 2500Mi
  service:
    authServerServiceName: auth-server
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
auth-server-key-rotation:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/certmanager
    tag: 1.0.0_dev
  keysLife: 23
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
client-api:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/client-api
    tag: 1.0.0_dev
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 400Mi
    requests:
      cpu: 1000m
      memory: 400Mi
  service:
    clientApiServerServiceName: client-api
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
config:
  adminPassword: Test1234#
  city: Austin
  configmap:
    cnAuthServerBackend: "auth-server:8080"
    cnSqlDbDialect: mysql
    cnSqlDbHost: my-release-mysql.default.svc.cluster.local
    cnSqlDbPort: 3306
    cnSqlDbName: jans
    cnSqlDbUser: jans
    cnSqlDbTimezone: UTC
    cnSqlPasswordFile: /etc/jans/conf/sql_password
    cnSqldbUserPassword: Test1234#
    cnCacheType: NATIVE_PERSISTENCE
    cnClientApiAdminCertCn: client-api
    cnClientApiApplicationCertCn: client-api
    cnClientApiBindIpAddresses: "*"
    cnClientApiServerUrl: "client-api:8443"
    cnConfigKubernetesConfigMap: cn
    cnCouchbaseBucketPrefix: jans
    cnCouchbaseCertFile: /etc/certs/couchbase.crt
    cnCouchbaseCrt: SWFtTm90YVNlcnZpY2VBY2NvdW50Q2hhbmdlTWV0b09uZQo=
    cnCouchbaseIndexNumReplica: 0
    cnCouchbasePassword: Test1234#
    cnCouchbasePasswordFile: /etc/jans/conf/couchbase_password
    cnCouchbaseSuperUser: admin
    cnCouchbaseSuperUserPassword: Test1234#
    cnCouchbaseSuperUserPasswordFile: /etc/jans/conf/couchbase_superuser_password
    cnCouchbaseUrl: cbjans.default.svc.cluster.local
    cnCouchbaseUser: jans
    # base64 string for the external signing jwks. Used when .global.cnExtSigningJwksUri is set.
    cnExtSigningJwksCrt: SWFtTm90YVNlcnZpY2VBY2NvdW50Q2hhbmdlTWV0b09uZQo=
    cnExtSigningJwksKey: SWFtTm90YVNlcnZpY2VBY2NvdW50Q2hhbmdlTWV0b09uZQo=
    # [google_secret_manager_envs] Envs related to using Google Secret Manager to store config and secret layer
    # Base64 encode service account. The sa must have roles/secretmanager.admin
    cnGoogleSecretManagerServiceAccount: SWFtTm90YVNlcnZpY2VBY2NvdW50Q2hhbmdlTWV0b09uZQo=
    cnGoogleProjectId: google-project-to-save-config-and-secrets-to
    cnSecretGoogleSecretVersionId: "latest"
    cnSecretGoogleSecretNamePrefix: jans
    cnGoogleSecretManagerPassPhrase: Test1234#
    cnConfigGoogleSecretVersionId: "latest"
    cnConfigGoogleSecretNamePrefix: jans
    # [google_secret_manager_envs] END
    cnLdapUrl: "opendj:1636"
    cnMaxRamPercent: "75.0"
    cnPersistenceLdapMapping: default
    cnRedisSentinelGroup: ""
    cnRedisSslTruststore: ""
    cnRedisType: STANDALONE
    cnRedisUrl: "redis.redis.svc.cluster.local:6379"
    cnRedisUseSsl: false
    cnSecretKubernetesSecret: cn
    containerMetadataName: kubernetes
    lbAddr: ""
    ldapServiceName: opendj
  countryCode: US
  email: support@jans.io
  image:
    repository: janssenproject/configuration-manager
    tag: 1.0.0_dev
  ldapPassword: Test1234#
  orgName: Janssen
  redisPassword: Test1234#
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
  state: TX
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
  dnsPolicy: ""
  dnsConfig: {}
config-api:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/config-api
    tag: 1.0.0_dev
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 400Mi
    requests:
      cpu: 1000m
      memory: 400Mi
  service:
    configApiServerServiceName: config-api
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
fido2:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/fido2
    tag: 1.0.0_dev
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  service:
    fido2ServiceName: fido2
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
global:
  alb:
    ingress: false
  auth-server:
    enabled: true
  auth-server-key-rotation:
    enabled: false
  awsStorageType: io1
  azureStorageAccountType: Standard_LRS
  azureStorageKind: Managed
  client-api:
    enabled: false
  cloud:
    testEnviroment: false
  cnPersistenceType: ldap
  cnExtSigningJwksUri: ""
  config:
    enabled: true
  #google/kubernetes
  configAdapterName: kubernetes
  #google/kubernetes
  configSecretAdapter: kubernetes
  # [google_secret_manager_envs] Envs related to using Google Secret Manager to store config and secret layer
  # Base64 encode service account. The sa must have roles/secretmanager.admin
  cnGoogleApplicationCredentials: /etc/jans/conf/google-credentials.json
  # [google_secret_manager_envs] END
  config-api:
    enabled: true
  fqdn: demoexample.jans.io
  fido2:
    enabled: false
  gcePdStorageType: pd-standard
  isFqdnRegistered: false
  istio:
    enabled: false
    ingress: false
    namespace: istio-system
  lbIp: "22.22.22.22"
  nginx-ingress:
    enabled: true
  opendj:
    enabled: true
  distribution: default
  persistence:
    enabled: true
  scim:
    enabled: false
  storageClass:
    allowVolumeExpansion: true
    allowedTopologies: []
    mountOptions:
    - debug
    parameters: {}
    #parameters:
      #fsType: ""
      #kind: ""
      #pool: ""
      #storageAccountType: ""
      #type: ""
    provisioner: microk8s.io/hostpath
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
  upgrade:
    enabled: false
nginx-ingress:
  ingress:
    # /.well-known/openid-configuration
    openidConfigEnabled: true
    # /.well-known/uma2-configuration
    uma2ConfigEnabled: true
    # /.well-known/webfinger
    webfingerEnabled: true
    # /.well-known/simple-web-discovery
    webdiscoveryEnabled: true
    # /.well-known/scim-configuration
    scimConfigEnabled: false
    # /jans-scim
    scimEnabled: false
    # /jans-config-api
    configApiEnabled: true
    # /.well-known/fido-configuration
    u2fConfigEnabled: true
    # /.well-known/fido2-configuration
    fido2ConfigEnabled: false
    # /jans-auth
    authServerEnabled: true
    #/jans-auth/restv1/token
    authServerProtectedToken: false
    #/jans-auth/restv1/register
    authServerProtectedRegister: false
    # in the format of {cert-manager.io/cluster-issuer: nameOfClusterIssuer, kubernetes.io/tls-acme: "true"}
    additionalAnnotations: {}
    path: /
    hosts:
    - demoexample.jans.io
    tls:
    - secretName: tls-certificate
      hosts:
      - demoexample.jans.io
opendj:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: gluufederation/opendj
    tag: 5.0.0_dev
  multiCluster:
    enabled: false
    serfAdvertiseAddr: "firstldap.jans.io:30946"
    serfKey: Z51b6PgKU1MZ75NCZOTGGoc0LP2OF3qvF6sjxHyQCYk=
    serfPeers:
    - "firstldap.jans.io:30946"
    - "secondldap.jans.io:31946"
  persistence:
    size: 5Gi
  ports:
    tcp-admin:
      nodePort: ""
      port: 4444
      protocol: TCP
      targetPort: 4444
    tcp-ldap:
      nodePort: ""
      port: 1389
      protocol: TCP
      targetPort: 1389
    tcp-ldaps:
      nodePort: ""
      port: 1636
      protocol: TCP
      targetPort: 1636
    tcp-repl:
      nodePort: ""
      port: 8989
      protocol: TCP
      targetPort: 8989
    tcp-serf:
      nodePort: ""
      port: 7946
      protocol: TCP
      targetPort: 7946
    udp-serf:
      nodePort: ""
      port: 7946
      protocol: UDP
      targetPort: 7946
  replicas: 1
  resources:
    limits:
      cpu: 1500m
      memory: 2000Mi
    requests:
      cpu: 1500m
      memory: 2000Mi
  service:
    ldapServiceName: opendj
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
persistence:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/persistence-loader
    tag: 1.0.0_dev
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
scim:
  dnsPolicy: ""
  dnsConfig: {}
  image:
    pullPolicy: Always
    repository: janssenproject/scim
    tag: 1.0.0_dev
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 1000Mi
  service:
    scimServiceName: scim
#  livenessProbe:
#    initialDelaySeconds: 25
#  readinessProbe:
#    initialDelaySeconds: 30
  volumes: []
    # Configure any additional volumes that need to be attached to the pod
  volumeMounts: []
    # Configure any additional volumesMounts that need to be attached to the containers
