apiVersion: v1
entries:
  jans:
  - annotations:
      artifacthub.io/changes: |
        - Janssen 1.0 under dev charts
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0_dev
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0_dev
        - name:  client-api
          image: janssenproject/client-api:1.0.0_dev
        - name: configuration-manager
          image: janssenproject/configuration-manager:1.0.0_dev
        - name:  config-api
          image: janssenproject/config-api:1.0.0_dev
        - name: fido2
          image: janssenproject/fido2:1.0.0_dev
        - name: opendj
          image: gluufedration/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0_dev
        - name: scim
          image: janssenproject/scim:1.0.0_dev
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
    apiVersion: v2
    appVersion: 1.0.0-a4
    created: "2021-04-23T08:52:18.064375833Z"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 1.0.0-a4
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 1.0.0-a4
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 1.0.0-a4
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 1.0.0-a4
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 1.0.0-a4
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 1.0.0-a4
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 1.0.0-a4
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 1.0.0-a4
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 1.0.0-a4
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 1.0.0-a4
    - condition: global.istio.ingress
      name: cn-istio-ingress
      repository: ""
      version: 1.0.0-a4
    description: Janssen Authorization server
    digest: 65f2cfdc05a1cf4e63d3c5e883fe2309c2991fd1c9f187021d6f63694646c83b
    home: https://github.com/JanssenProject/jans-cloud-native
    icon: https://avatars.githubusercontent.com/u/68292770?s=200&v=4
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - email: mo@gluu.org
      name: moabu
    name: jans
    sources:
    - https://github.com/JanssenProject/jans-cloud-native/charts
    urls:
    - jans-1.0.0-a4.tgz
    version: 1.0.0-a4
generated: "2021-04-23T08:52:18.055950424Z"
